DROP TABLE towar_koszyk CASCADE CONSTRAINTS;

DROP TABLE producent_towar CASCADE CONSTRAINTS;

DROP TABLE faktura CASCADE CONSTRAINTS;

DROP TABLE platnosc CASCADE CONSTRAINTS;

DROP TABLE koszyk CASCADE CONSTRAINTS;

DROP TABLE kupujacy CASCADE CONSTRAINTS;

DROP TABLE towar CASCADE CONSTRAINTS;

DROP TABLE sprzedajacy CASCADE CONSTRAINTS;

DROP TABLE uzytkownik CASCADE CONSTRAINTS;

DROP TABLE adres CASCADE CONSTRAINTS;

DROP TABLE dostawa CASCADE CONSTRAINTS;

DROP TABLE producent CASCADE CONSTRAINTS;

DROP TABLE kategoria CASCADE CONSTRAINTS;

DROP TABLE sklep CASCADE CONSTRAINTS;