CREATE SEQUENCE Sklep_id
MINVALUE 0
MAXVALUE 99999
START WITH 1
INCREMENT BY  1;

CREATE SEQUENCE Kategoria_id
MINVALUE 0
MAXVALUE 99999
START WITH 1
INCREMENT BY  1;

CREATE SEQUENCE Producent_id
MINVALUE 0
MAXVALUE 99999
START WITH 1
INCREMENT BY  1;

CREATE SEQUENCE Dostawa_id
MINVALUE 0
MAXVALUE 99999
START WITH 1
INCREMENT BY  1;

CREATE SEQUENCE Adres_id
MINVALUE 0
MAXVALUE 99999
START WITH 1
INCREMENT BY  1;

CREATE SEQUENCE Uzytkownik_id
MINVALUE 0
MAXVALUE 99999
START WITH 1
INCREMENT BY  1;

CREATE SEQUENCE Towar_id
MINVALUE 0
MAXVALUE 99999
START WITH 1
INCREMENT BY  1;

CREATE SEQUENCE Koszyk_id
MINVALUE 0
MAXVALUE 99999
START WITH 1
INCREMENT BY  1;

CREATE SEQUENCE Platnosc_id
MINVALUE 0
MAXVALUE 99999
START WITH 1
INCREMENT BY  1;

CREATE SEQUENCE Faktura_id
MINVALUE 0
MAXVALUE 99999
START WITH 1
INCREMENT BY  1;